spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
  application:
    name: reserve-application

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

    export:
      prometheus:
        enabled: true

application:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reserve?serverTimezone=UTC&rewriteBatchedStatements=true&useServerPrepStmts=true
    username: root
    password: root

logging:
  level:
    org.hibernate.orm.jdbc.batch: DEBUG
    org.hibernate.engine.jdbc.batch.internal: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
